filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/neutron/*
    - /var/log/httpd/error_log
    - /var/log/glance/api.log
    - /var/log/keystone/keystone.log
    - /var/log/nova/nova-conductor.log
    - /var/log/nova/nova-placement-api.log
    - /var/log/nova/nova-consoleauth.log
    - /var/log/nova/nova-scheduler.log
    - /var/log/cinder/api.log
    - /var/log/cinder/scheduler.log

  multiline.pattern:  '^\t|Exception|more|^$|^Caused|Error|^[[:space:]]org|ERROR|WARNING'
  multiline.negate: false
  multiline.match: after
  multiline.max_lines: 500
  multiline.timeout: 2s
  include_lines: ["ERROR", "Exception", "failed", "execution"]
  tail_files: true
  scan_frequency: 1s
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3
setup.kibana:
output.logstash:
  hosts: ["elk.alv.pub:5044"]
